image: gradle:5.6-jdk8

variables:
  # Set the location of the dependency cache to a local directory, so that it
  # can be cached between GitLab Continous Integration Jobs.
  GRADLE_USER_HOME: '.gradle'
  SONAR: 'https://sonarqube.ow2.org'

cache:
  paths:
    # Cache the downloaded dependencies and plugins between builds.
    - '$GRADLE_USER_HOME'

build:
  script:
    - gradle build
    - gradle test jacocoTestCoverageVerification
    - gradle uploadArchives
    - 'gradle sonarqube -Dsonar.host.url=$SONAR'
